### PR TITLE
[feature] build with boring crypto where available

### PR DESCRIPTION
**Pull request by dweomer**
```
$ ./dist/hauler_linux_amd64_v1/hauler version
 __    __       ___       __    __   __       _______ .______
|  |  |  |     /   \     |  |  |  | |  |     |   ____||   _  \
|  |__|  |    /  ^  \    |  |  |  | |  |     |  |__   |  |_)  |
|   __   |   /  /_\  \   |  |  |  | |  |     |   __|  |      /
|  |  |  |  /  _____  \  |  `--'  | |  `----.|  |____ |  |\  \----.
|__|  |__| /__/     \__\  \______/  |_______||_______|| _| `._____|
hauler: Airgap Swiss Army Knife

GitVersion:    1.1.0-rc.10-SNAPSHOT-6031d80
GitCommit:     6031d80
GitTreeState:  clean
BuildDate:     2024-10-03T00:48:50Z
GoVersion:     go1.23.1 X:boringcrypto
Compiler:      gc
Platform:      linux/amd64
```

### CODE REVIEW

**Comment by bgulla** [comment]
i like dis.

**Review by zackbradys — APPROVED** [review]
LGTM!! 🚀

**Review by zackbradys — CHANGES_REQUESTED** [review]
Please close and reopen with signed commits.

**Comment by dweomer** [comment]
> Please close and reopen with signed commits.

it is signed, just unverified

**Pull request closed without merging**
