### PR TITLE
enable docker load for hauler tarballs

### LINKED ISSUE #276: [feature] support `docker load` semantics for hauler bundles
**Is this RFE related to an Existing Problem? If so, please describe:**

RKE2 assumes a `manifest.json` at the top level of the tarball for the `rke2-runtime` image via [rancher/wharfie](https://github.com/rancher/wharfie). For all other images, RKE2 (and k3s) seem to have no issue importing our `oci-layout` tarballs. We could lobby to have wharfie be more accepting but I think it behooves us to render a `manifest.json` at the top of our `hauler store`, which is in `oci-layout`, which will enable `/var/lib/rancher/rke2/agent/images` drop-ins straight from hauler for the RKE2 bootstrap image (`rke2-runtime`). Moreover, this should enable `docker load` of uncompressed hauler tarballs.

**Describe Proposed Solution(s):**

Render entries in `${hauler-store}/manifest.json` for every platform of every container image in the store, aka, "name", "config", "layer(s)". For example, here is the `manifest.json` created by [`ctr image export`](https://github.com/containerd/containerd/blob/v1.7.20/cmd/ctr/commands/images/export.go) for the RKE2 v1.28.11+rke2r1 `rancher/rke2-runtime` image for the `linux/amd64` platform:
```json
[
  {
    "Config": "blobs/sha256/6fcb0bf266887eaeaf3c3fa09d28a760b694c82ecf0382fd6e3becbe3ef1abf6",
    "RepoTags": [
      "rancher/rke2-runtime:v1.28.11-rke2r1"
    ],
    "Layers": [
      "blobs/sha256/9985469ebb41c51e0d1c59c8dfccaefc225b6615d911da001c9734d6e17b4014"
    ]
  }
]
```

**Describe Possible Alternatives:**

- Push [rancher/wharfie](https://github.com/rancher/wharfie) to be more compatible with what containerd's `ctr image import` currently accepts.

**Additional Context:**

It should be pretty easy to validate that our solution is working correctly, and hence will work within RKE2, by running wharfie in docker container with network=none, e.g.:
```bash
# where ./images/ is a directory containing the hauler tarball containing `rancher/rke2-runtime` content
docker run --rm -it --network=none -v ./images:/images dweomer/wharfie:v0.6.6-amd64 --images-dir /images rancher/rke2-runtime:v1.28.11-rke2r1 /root
```
But also, too:
```bash
docker image load haul.tar # after uncompressing via zstd -d
```

### PR DESCRIPTION
**Pull request by dweomer**
- fixes #276

Signed-off-by: Jacob Blain Christen <jacob.blain.christen@ranchergovernment.com>

### CODE REVIEW

**Comment by atoy3731** [comment]
Seeing one issue with `docker save` vs `hauler store save` with hauler bundles.

When RKE2/K3s loads the images, the repo metadata is lost. Using `crictl images`:
`docker save`:
```
harbor.atoy.dev/public/dnsutils                                      1.0                                        2b62dfbe8a9a9       76.4MB
```

`hauler store save`:
```
docker.io/public/dnsutils                                            1.0                                        2b62dfbe8a9a9       76.4MB
```

That probably means hauler store add image needs some (potentially option?) to maintain the repo.

**Comment by zackbradys** [comment]
Right now that is the functionality of `hauler`. When you `hauler store add`, it removes the `registry` from the image reference and when you `hauler store copy`, it adds the specified `registry` to the image reference. 

We probably need to have a conversation about how we want to do this in the future and would require a larger lift. There are a few open and related tickets to this too. @atoy3731 @dweomer

**Comment by dweomer** [comment]
> Right now that is the functionality of `hauler`. When you `hauler store add`, it removes the `registry` from the image reference and when you `hauler store copy`, it adds the specified `registry` to the image reference.
> 
> We probably need to have a conversation about how we want to do this in the future and would require a larger lift. There are a few open and related tickets to this too. @atoy3731 @dweomer

can we get a bug report on this behavior?

**Comment by amartin120** [comment]
It's intended, albeit an outdated idea.  When Hauler pulls in an image into its store, it tosses out the registry from the image ref on purpose.  Mostly because of an idea that Haulers goal was to snag and relocate images to another registry and therefore the origin registry wasn't really needed.

Now that Hauler does more than move images from registry to registry, we should have a conversation about changing this.  It's handled in the cosign fork and not Hauler itself.  (plus it's part of the upstream cosign PR)

If you inspect the index.json in the oci layout.  You'll see in the annotations that all of the image refs are just stripped of the registry.  So now that we're using docker load, I guess it's adding the default of `docker.io`.

**Comment by zackbradys** [comment]
Thanks for the deeper dive on it @amartin120. Agreed that we need to chat on it. Hauler meeting next week?

@dweomer there are two or three discussions and open `RFEs` on it. 

I wouldn't classify it as a `bug` since it is how `hauler` is intended to function as now.

**Comment by zackbradys** [comment]
@dweomer are you expecting any more updates to this PR or is it ready to be reviewed/tested/merged?

**Review by amartin120 — APPROVED** [review]
LGTM.  There will be a follow-up PR for adjusting the imageRef to use a new annotation described here... https://github.com/hauler-dev/hauler/pull/322

**Pull request merged**
